# Image processing configuration
topHeight: 10 # height from the bottom of the image to search for the top intersection of the line
botHeight: 0 # height from the bottom of the image to search for the bottom intersection of the line

lineThickness: 2 # minimum thickness in pixels (see resize_h/w) of line to be detected

greenDifference: 10 # min diff between g and r/b values (10 for warehouse)
blueRedDifference: 100 # max diff between r and b values

bottomLineMultiplier: 0.82 # adjusts the dimensions of the bottom line to compensate for perspective of the camera
centeringMultiplier: 0.4 # weight of centering (aligning the middle of the robot to the line)

resizeHeight: 30 # resized image height (should be 4:3)
resizeWidth: 40 # resized image width